apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datum-gateway
spec:
  replicas: 1
  template:
    spec:
      initContainers:
        - name: copy-config
          image: us-east1-docker.pkg.dev/datum-stack-k8s-test/datum-stack-k8s-repo/datum-docker:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          command: 
            - sh
            - -c
            - |
              cp /app/datum_gateway /mnt/app/datum_gateway
              chown -R 1000:1000 /mnt/app
          volumeMounts:
            - name: datum-data
              mountPath: /mnt/app
          securityContext:
            runAsNonRoot: false
            runAsUser: 0
            allowPrivilegeEscalation: false
      containers:
        - name: datum-gateway
          image: us-east1-docker.pkg.dev/datum-stack-k8s-test/datum-stack-k8s-repo/datum-docker:latest
          resources:
            requests:
              memory: "4Gi"
              cpu: "2000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
  volumeClaimTemplates:
  - metadata:
      name: datum-data
    spec:
      storageClassName: standard-rwo
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 16Gi
