apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: knots-bitcoind
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: knots-bitcoind
          image: localhost:32000/retropex/docker-bitcoind:28.1
  volumeClaimTemplates:
  - metadata:
      name: bitcoind-data
    spec:
      storageClassName: mayastor
      accessModes: 
        - ReadWriteOnce
      resources:
        requests:
          storage: 750Gi