apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: datum-gateway
spec:
  template:
    spec:
      containers:
        - name: datum-gateway
          image: localhost:32000/retropex/datum-docker:latest
          command: ["/bin/sh"]
          args: ["-c", "sleep 3600"]
